-- AlterTable
ALTER TABLE "User" ADD COLUMN "trialStartedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "trialEndsAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "trialUsed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "trialClosedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "postsToday" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "postsTodayResetAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "aiCallsUsed" INTEGER NOT NULL DEFAULT 0;
